### ISSUE TITLE
forwarding client

### ISSUE THREAD

**Issue by kr** [kr/beanstalkd#13]
It would be nice to have a client that just forwards jobs from one beanstalkd instance to another. See http://groups.google.com/group/beanstalk-talk/t/984bfc8037847e53 for some motivation for this setup.

**Comment by JensRantil** [comment]
@kr This _very_ easy to implement using a simple python script or whatever. To keep this project focused, I suggest this feature request is closed.

**Comment by kr** [comment]
Nice. Thanks for spotting this. :)
