### ISSUE TITLE
Attempt to unlock a mutex which is locked by another thread

### ISSUE THREAD

**Issue by giovannelli** [kr/beanstalkd#140]
Hi,
i'm using beanstalkd in one of my rails projects, i'm having a problem with threads.

I've many threads which connect to a tube in order to empty the queue and only one process filling the queue. Some times i receive this error:  **Attempt to unlock a mutex which is locked by another thread**.

This is the exception backtrace:

<pre>
/mnt/apps/pulsarplatform/shared/bundle/ruby/1.9.1/gems/beanstalk-client-1.1.1/lib/beanstalk-client/connection.rb:199:in `unlock'
/mnt/apps/pulsarplatform/shared/bundle/ruby/1.9.1/gems/beanstalk-client-1.1.1/lib/beanstalk-client/connection.rb:199:in `ensure in interact'
/mnt/apps/pulsarplatform/shared/bundle/ruby/1.9.1/gems/beanstalk-client-1.1.1/lib/beanstalk-client/connection.rb:199:in `interact'
/mnt/apps/pulsarplatform/shared/bundle/ruby/1.9.1/gems/beanstalk-client-1.1.1/lib/beanstalk-client/connection.rb:173:in `stats_tube'
/mnt/apps/pulsarplatform/shared/bundle/ruby/1.9.1/gems/beanstalk-client-1.1.1/lib/beanstalk-client/connection.rb:394:in `call_wrap'
/mnt/apps/pulsarplatform/shared/bundle/ruby/1.9.1/gems/beanstalk-client-1.1.1/lib/beanstalk-client/connection.rb:424:in `block (2 levels) in send_to_all_conns'
/mnt/apps/pulsarplatform/shared/bundle/ruby/1.9.1/gems/beanstalk-client-1.1.1/lib/beanstalk-client/connection.rb:436:in `block in map_hash'
/mnt/apps/pulsarplatform/shared/bundle/ruby/1.9.1/gems/beanstalk-client-1.1.1/lib/beanstalk-client/connection.rb:436:in `each'
/mnt/apps/pulsarplatform/shared/bundle/ruby/1.9.1/gems/beanstalk-client-1.1.1/lib/beanstalk-client/connection.rb:436:in `map'
/mnt/apps/pulsarplatform/shared/bundle/ruby/1.9.1/gems/beanstalk-client-1.1.1/lib/beanstalk-client/connection.rb:436:in `map_hash'
/mnt/apps/pulsarplatform/shared/bundle/ruby/1.9.1/gems/beanstalk-client-1.1.1/lib/beanstalk-client/connection.rb:424:in `block in send_to_all_conns'
/mnt/apps/pulsarplatform/shared/bundle/ruby/1.9.1/gems/beanstalk-client-1.1.1/lib/beanstalk-client/connection.rb:403:in `retry_wrap'
/mnt/apps/pulsarplatform/shared/bundle/ruby/1.9.1/gems/beanstalk-client-1.1.1/lib/beanstalk-client/connection.rb:424:in `send_to_all_conns'
/mnt/apps/pulsarplatform/shared/bundle/ruby/1.9.1/gems/beanstalk-client-1.1.1/lib/beanstalk-client/connection.rb:339:in `raw_stats_tube'
/mnt/apps/pulsarplatform/shared/bundle/ruby/1.9.1/gems/beanstalk-client-1.1.1/lib/beanstalk-client/connection.rb:343:in `stats_tube'
</pre>

Have some one of you ever had some similar issue?

Tnx

Duccio

**Comment by JensRantil** [comment]
@giovannelli @kr: This issue can be closed.
