### ISSUE TITLE
Use of 200-char tube name causes INTERNAL_ERROR

### ISSUE THREAD

**Issue by tdg5** [kr/beanstalkd#211]
Using a tube name that is 200 chars long returns INTERNAL_ERROR. The error should be reproducible with the following:
```
use xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
```

The error occurs at prot.c:343 and happens for one of two reasons, depending on your perspective.

Either prot.c:343 should use > instead of >=, like so:
```
if (r > LINE_BUF_SIZE) return reply_serr(c, MSG_INTERNAL_ERROR);
```

Or alternatively, LINE_BUF_SIZE could be increased from 208 to 209.

In my oppinion, prot.c:343 is the real issue. However, let me know what your preferred solution is and I can draft the appropriate pull request.

**Comment by kr** [comment]
Fixed in 2279f1815d33d1eddacbaaca0b09384c4c50c1f6.
