### ISSUE TITLE
Can't ignore tube with name 200 chars long

### ISSUE THREAD

**Issue by tdg5** [kr/beanstalkd#212]
Though it is possible to watch a tube with a name 200 char long, it is not possible to ignore that tube. Ignoring a tube of len 200 returns BAD_FORMAT.

I haven't been able to figure out why however since ignore seems to use the same pattern for checking the length of the tube name that watch uses. Len 199 does work for me, so probably a comparison type issue somewhere.

Ultimately, since a tube with a name 200 chars long cannot be used (as noted by #211), there's not much reason to watch such a tube until that is fixed.

You should be able to reproduce this issue with the following:
```
watch xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
ignore xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
```

For reference, I am using version 1.9+9+g157d88b on Ubuntu 12.04.

**Comment by kr** [comment]
Fixed in 2279f1815d33d1eddacbaaca0b09384c4c50c1f6.
