### ISSUE TITLE
reserve-with-timeout not working right

### ISSUE THREAD

**Issue by raulp** [kr/beanstalkd#239]
Hey  guys
I've tried to reserve with timeout and ... it did not worked as expected. Or maybe i did not understood correctly how this works:

stats-job 202
id: 202
tube: test
state: ready
pri: 1024
age: 5613
delay: 0
ttr: 60
time-left: 0
......

reserve-with-timeout 300
RESERVED 202 13323
stats-job 202
tube: test
state: reserved
pri: 1024
age: 5613
delay: 0
ttr: 60
time-left: 58

My question is ... why the TTR was not changed ? Shouldn't that change when use reserve-with-timeout ?

Thanks

**Comment by JensRantil** [comment]
@raulp @kr This issue can be closed.
