### ISSUE TITLE
this is my error when i issue the command "make" to install dislocker

### ISSUE THREAD

**Issue by AOSumague** [kr/beanstalkd#251]
cc1: warnings being treated as errors
outputs/fuse/fuse.c: In function ‘fs_fsync’:
outputs/fuse/fuse.c:524: warning: implicit declaration of function ‘fdatasync’
make: *** [outputs/fuse/fuse.o] Error 1
Alfredo-Sumagues-MacBook:src alfredosumague$

**Comment by kr** [comment]
Hi there! It looks like the code you're trying to compile is from a different program. This is beanstalkd. We don't have a file called outputs/fuse/fuse.c. 😅

I would like to point you in the right direction, but I'm afraid I have no idea what code that is. Sorry I can't be more helpful. Good luck!
