### ISSUE TITLE
When I use the 'reserve' operation in beanstalked, it is blocked for a long time

### ISSUE THREAD

**Issue by GeekTemo** [kr/beanstalkd#256]
I need to use beanstalked in my project.So I download the 1.1 version. I use the beanstalkc for python client. A simple Producer-Consumer model.

Producer:

       import beanstalkc
       beanstalk = beanstalkc.Connection('localhost')
       beanstalk.use('foo')
       beanstalk.put('hello')
       beanstalk.put('world')
Consumer:

      import beanstalkc
      beanstalk.use('foo')
      beanstalk = beanstalkc.Connection('localhost')
      job = beanstalk.reserve()
But the reserve operation is blocked for a long time.Has anybody encounter this problem?

**Comment by JensRantil** [comment]
@GeekTemo @kr: This can be closed, right?

**Comment by kr** [comment]
Yup. Thanks @JensRantil. :)
