### ISSUE TITLE
Multiple tubes or multiple workers on the same tube?

### ISSUE THREAD

**Issue by skedone** [kr/beanstalkd#257]
Hi, 
 I experienced some memory issue regarding the creation of a lot of tubes (around 50 tubes). 
I run beanstalkd on a t2.small ec2-istance (2 GB of RAM and low thought-put, ubuntu 14.04 LTS). 

In my scenario I have around 50 tubes and workers attached, those workers use PHP with pda/pheanstalk. The average of messages is really low (20-25 message a minute) but it seems that I have a lot of disconnection and beanstalkd process consume a lot of virtual memory (not php workers, but beanstalkd itself).

In order to design well the application, I'm considering to have less tubes (with more average per tube), also because it is really easy to scale out workers, but not so easy to scale out beanstalkd.
I also consider it due to open connections: less workers means less connection (maybe also less memory?).

Am I wrong for considering to keep less tubes and add more workers per tube?

Thank you in advice!
 Edoardo

**Comment by ifduyue** [comment]
A connection can watch more than one tubes.

**Comment by skedone** [comment]
Thanks :+1: ! I forgot to close this issue.
