### ISSUE TITLE
Batch multiple commands in one request

### ISSUE THREAD

**Issue by r3wt** [kr/beanstalkd#261]
connect + use + put + ignore + close all in one socket write. is it possible?

**Comment by ifduyue** [comment]
Currently, no.

**Comment by kr** [comment]
Yes, it's possible.

The way to do it depends on the programming environment you're using in your client. In general, you can prepare all the commands you want to run in a single buffer, then call [write](http://man.cx/write(2)) from that buffer to the socket file descriptor. Be aware that this doesn't guarantee the write will complete in a single syscall, or that the entire buffer will fit in a single network packet. Also be aware that the commands will still execute individually by the server as it reads them—if what you want is atomicity for the group of commands, like a database transaction, beanstalkd doesn't provide that.

**Comment by kr** [comment]
Ok, I'm going to close this. The original question was for something beanstalkd already provides, so we should be in good shape! :)
