### ISSUE TITLE
Beanstalkd HA - node crash / disk failure

### ISSUE THREAD

**Issue by trompx** [kr/beanstalkd#268]
Hello !

I was wondering how you were handling cases like node crash / disk failure ?

Shoud I backup binlog files ? I am wondering about the utility, I have no example workload as I am still developping the app so depending on the number of workers, the queue might always be near empty or with enough jobs to keep my workers busy for 15 minutes... The ideal would be to have a synchronous backup somewhere else but I don't know if it is the way to go.

Or maybe should I just use redis or external service as SQS to get this "not losing any data" feature. Would prefer redis but it seems it is not the best practice : https://news.ycombinator.com/item?id=1084029

Any tips would be great.

Thank you

**Comment by JensRantil** [comment]
Hey, beanstalkd doesn't support any high-availability features. What you _could_ do would be to enable binlogging (`-b` flag) and use mirrored harddrives.

**Comment by JensRantil** [comment]
...also, feel free to close this I I've answered your question.

**Comment by kr** [comment]
Yeah, this is outside the scope of beanstalkd. It's best for helping to schedule work, not for storing important data.
