### ISSUE TITLE
Sequence numbers / Synchronous clients?

### ISSUE THREAD

**Issue by thijsterlouw** [kr/beanstalkd#27]
I just read the protocol discription for Beanstalkd. The project looks great and the protocol is really simple. Should be very straightforward to implement in a language such as Erlang. The only problem I could see is the lack of sequence numbers. This basically would force synchronous usage for the clients of Beanstalkd ? Do you have any plans for a binary protocol with sequence numbers?

**Comment by JensRantil** [comment]
@thijsterlouw @kr I suggest this issue can be closed, right?

**Comment by kr** [comment]
Yeah, this would involve a major redesign of the protocol. The existing protocol appears to be good enough in practice.
