### ISSUE TITLE
Beanstalkd - job priorities between tubes and for one tube. BUG?

### ISSUE THREAD

**Issue by Perlover** [kr/beanstalkd#272]
Hi!

I have read protocol.txt and i work a long time with beanstalkd.
But to be reading the documentation i thought that if i watch one tube and there jobs with different priorities - i will get in 'reserve' command a first high-priority job before and only if i have same priority jobs - i will get a first from FIFO order.

But i saw the sources of version 1.9 and now i understand this as following:

The priority works only when we watch more than one tube! If we watch only one tube - i will get everytime first job from FIFO despite the priority!

Example: https://github.com/kr/beanstalkd/blob/v1.9/prot.c

The function process_queue() (line 419) calls the next_eligible_job()
The next_eligible_job() (line 395) sees all watched tubes and compares priority only of first element of each tube (line 409) and sees the first jobs from each watched tube and uses high-priority job from them! I not correctly understand the documentation? Where problem? Or everybody thinks except me that a priority works only between watched tubes?

**Comment by kr** [comment]
The priority works within a single tube. Note that the items in a tube are kept in a min-heap ordered by priority, then id. So `t->ready.data[0]` (line 408) is the most high-priority job in the tube.

**Comment by r3wt** [comment]
the highest priority job is always the first item in the tube. understand now?

**Comment by Perlover** [comment]
Thank you very much!
I found it!
