### ISSUE TITLE
Algorithm for binlog compaction seems very conservative

### ISSUE THREAD

**Issue by Minnozz** [kr/beanstalkd#276]
In our application we use Beanstalk for jobs with potentially very long delay times (usually zero delay, 1 hour, or 24 hours, but some up to 1 year). I assume this is what leads to very fragmented binlog files.

Our current beanstalkd contains 4.2 million jobs (of ~250 bytes each; so ~1GB of useful data), but the cumulative size of the binlogs is 500GB. The binlog size is the default value (~10.5MB). Since the last restart, 1.3 billion jobs have been put, and 2.5 billion records have been written to the binlog.

beanstalkd runs with the default settings for compaction (= on), but the 'stats' command says 0 records have been migrated ("binlog-records-migrated: 0").

I wonder why no records have ever been migrated. By my estimate, the ratio of active data vs. empty space in the binlog is 1:500. Am I missing something?

The full output of the 'stats' command:
```
current-jobs-urgent: 353
current-jobs-ready: 353
current-jobs-reserved: 497
current-jobs-delayed: 4250127
current-jobs-buried: 2
cmd-put: 1295628675
cmd-peek: 0
cmd-peek-ready: 0
cmd-peek-delayed: 0
cmd-peek-buried: 0
cmd-reserve: 0
cmd-reserve-with-timeout: 1295181260
cmd-delete: 1294385177
cmd-release: 234225
cmd-use: 22636250
cmd-watch: 133269
cmd-ignore: 944
cmd-bury: 2
cmd-kick: 0
cmd-touch: 1708911
cmd-stats: 4
cmd-stats-job: 0
cmd-stats-tube: 74119673
cmd-list-tubes: 1
cmd-list-tube-used: 0
cmd-list-tubes-watched: 0
cmd-pause-tube: 0
job-timeouts: 3
total-jobs: 1295628675
max-job-size: 65535
current-tubes: 250
current-connections: 161
current-producers: 145
current-workers: 6
current-waiting: 6
total-connections: 2634249
pid: 4617
version: 1.10
rusage-utime: 278654.613059
rusage-stime: 145674.274144
uptime: 8838964
binlog-oldest-index: 28454
binlog-current-index: 69111
binlog-records-migrated: 0
binlog-records-written: 2590013855
binlog-max-size: 10485760
id: 29b43be8a8a89353
hostname: ***
```

**Comment by kr** [comment]
The target ratio of live data to unused space is less than 1/2. If your log is 500 times the size of the active data, that is not intended behavior with compaction turned on. It is also strange that binlog-records-migrated is 0.

What are the exact command line flags this beanstalkd is running with? (You can get this on the system where beanstalkd is running with the command `ps -fp 4617`.)

**Comment by Minnozz** [comment]
We are running beanstalkd as follows: `/usr/local/bin/beanstalkd -p 12345 -u nobody -b /data/beanstalkd/application_name/`

**Comment by Minnozz** [comment]
After looking at the `ratio` code again, I realised that the amount of binlog files (41101) times the binlog size (10485760) is ~2^39, which overflows the 32 bit integer `n`. This probably causes this behaviour.

Can we use a 64 bit integer for the ratio calculation?

**Comment by Minnozz** [comment]
Also, Wal.resv and Wal.alive should probably be 64 bit (unsigned) integers to support having more than ~4.3 GB of data in beanstalkd

**Comment by kr** [comment]
> ~2^39, which overflows the 32 bit integer `n`.

> Can we use a 64 bit integer for the ratio calculation?

> Also, `Wal.resv` and `Wal.alive` 

Good catch. They should definitely be 64 bits.
