### ISSUE TITLE
Beanstalk Server In Node.js

### ISSUE THREAD

**Issue by daarond** [kr/beanstalkd#281]
I created a beanstalk server in node.js:
https://github.com/daarond/beanstalkd-node

While the performance will never match the compiled version, it may be useful for non-production application testing and windows systems.

**Comment by JensRantil** [comment]
@daarond Feel free to send announce your project on the mailing list. You can also list your project [here](https://github.com/kr/beanstalkd/wiki/Tools).

I suggest this issue can be closed.

**Comment by daarond** [comment]
Thanks for letting me know
