### ISSUE TITLE
Delete a reserved job?

### ISSUE THREAD

**Issue by warroyo** [kr/beanstalkd#286]
I cant seem to find this functionality anywhere in the docs. what I would like to be able to do is to stop a reserved job using the `id`. Is this functionality available? my use case is that I would like a user to be able to cancel a running job.

**Comment by JensRantil** [comment]
@warroyo Your worker could periodically `touch` its reserved job. If it is deleted, the `touch` command will return `NOT_FOUND` and you'll know it's cancelled by a user.

**Comment by warroyo** [comment]
I ended up adding some logic to set a value in my database that if set tells the job to stop running.

**Comment by patrickkw** [comment]
If there are many clients connected to beanstalkd, and one of the clients (client-A) has reserved `job id=1`, can other clients (client-B, C, etc) delete the job (`id=1`) reserved by client-A?

According to the beanstalkd `doc/protocol.txt` document, `line-265`, it seems that it is not possible. It says the client can only delete a job reserved by itself.

In my use case, the job is a task which will take a very long time to run. Sometime when the worker is still running the task, the user want to stop the job. If I kill the worker process directly, the job will be released back to the ready queue, and it will be reserved and processed by other workers. If a job can only be deleted by the worker who reserved it, and the worker is busy processing the job and unable to respond to any signal from other process, there is no way for us to delete the job.

Is there any function that can delete a job reserved by other clients?

**Comment by JensRantil** [comment]
> Is there any function that can delete a job reserved by other clients?

No. And the reason for that not being supported is because it leads to an inherent risk of race condition where one client delete another client's job.
