### ISSUE TITLE
Protocol doc reference improvement proposal

### ISSUE THREAD

**Issue by JensRantil** [kr/beanstalkd#287]
I tend to go back to the [protocol doc](https://raw.githubusercontent.com/kr/beanstalkd/master/doc/protocol.txt) every now and then. Generally it's super well written, explaining the various job states etc.

Nowadays, I'm fairly confident about the overall structure of beanstalk. This means I mostly use the protocol document for reference. I guess you could call me a power user. However, every time I open up the document it nags me that it's not optimized to be used as a reference. More specifically, skimming through all the commands is hard answering questions such as

> I know there's a command for pausing a tube - what was it?

> Which order were the parameters of `put` in?

> Which stats commands are there?

I have no problem with ASCII per se, but the command examples simply blend in really well with the rest of the document. Inspired by Markdown, would you accept a pull request to the procol doc that indents all the protocol examples? We would go from

```
Worker Commands
---------------

A process that wants to consume jobs from the queue uses "reserve", "delete",
"release", and "bury". The first worker command, "reserve", looks like this:

reserve\r\n

Alternatively, you can specify a timeout as follows:

reserve-with-timeout <seconds>\r\n

This will return a newly-reserved job. If no job is available to be reserved,
beanstalkd will wait to send a response until one becomes available. Once a
job is reserved for the client, the client has limited time to run (TTR) the
job before the job times out. When the job times out, the server will put the
job back into the ready queue. Both the TTR and the actual time left can be
found in response to the stats-job command.
```
to
```
Worker Commands
---------------

A process that wants to consume jobs from the queue uses "reserve", "delete",
"release", and "bury". The first worker command, "reserve", looks like this:

    reserve\r\n

Alternatively, you can specify a timeout as follows:

    reserve-with-timeout <seconds>\r\n

This will return a newly-reserved job. If no job is available to be reserved,
beanstalkd will wait to send a response until one becomes available. Once a
job is reserved for the client, the client has limited time to run (TTR) the
job before the job times out. When the job times out, the server will put the
job back into the ready queue. Both the TTR and the actual time left can be
found in response to the stats-job command.
```

. What do you think?

**Comment by JensRantil** [comment]
@kr Ping.

**Comment by kr** [comment]
Sounds great. That would definitely improve readability. (Also, I think maybe we should ditch the actual markdown version of that file. It was a nice experiment, but the plain text version is the authoritative version, and the markdown isn't enough of an improvement to justify the extra work and confusion it causes.)

**Comment by sergeyklay** [comment]
Hey guys. Sorry for stupid question but I can't find protocol version. It seem to me it will be reasonable to put in a conspicuous place protocol version. What do you think about this?

**Comment by JensRantil** [comment]
> Sorry for stupid question but I can't find protocol version. It seem to me it will be reasonable to put in a conspicuous place protocol version. What do you think about this?

@sergeyklay See https://github.com/kr/beanstalkd/wiki/Client-Libraries#others. If still an issue, would you mind creating a [separate issue](https://github.com/kr/beanstalkd/issues/new) about is?

**Comment by JensRantil** [comment]
> Sounds great. That would definitely improve readability.

I'll get a pull request coming your way.

> (Also, I think maybe we should ditch the actual markdown version of that file. It was a nice experiment, but the plain text version is the authoritative version, and the markdown isn't enough of an improvement to justify the extra work and confusion it causes.)

Couldn't agree more. See #308.

**Comment by sergeyklay** [comment]
@JensRantil 
> The 1.3 protocol doc gives a complete description of the beanstalk protocol.

So v1.3 or v1.10 is the actual version of protocol. I'm still confused :neutral_face:

**Comment by JensRantil** [comment]
@sergeyklay See #287.
