### ISSUE TITLE
cann't kick buried job

### ISSUE THREAD

**Issue by selfchanger** [kr/beanstalkd#288]
hi,when i use bury() method to bury a job,everytime i use kick(10) method ,it returns 0,and i use statesTube() to see the state,it shows buried job doesn't decr,so i wonder why i cann't kick job

**Comment by JensRantil** [comment]
Hi. What happens if you telnet (or other solution) directly into beanstalkd and issue the commands there? Are you seeing the same issue? I suspect the bug you are experiencing could be an issue with the client library you are using. If so, it should be filed with the client library, not beanstalkd.

**Comment by JensRantil** [comment]
@kr I suggest this issue can be closed unless @selfchanger answers.

**Comment by kr** [comment]
:+1: Thanks @JensRantil for helping with triage.

**Comment by selfchanger** [comment]
@JensRantil @kr thanks a lot and sorry for not replying soon,i didn't try more because i didn't use it anymore,maybe you are right,anyway thank you!
