### ISSUE TITLE
How does beanstalk handle concurrent reserve requests?

### ISSUE THREAD

**Issue by aneesingh** [kr/beanstalkd#294]
I have multiple workers listening to same beanstalk queue.
If they call reserve on the queue simultaneously , will the same job be reserved and returned or only 1 request will be successful?

**Comment by JensRantil** [comment]
Only one request will be succesful.

**Comment by JensRantil** [comment]
@aneesingh Did I answer you question? If so, feel free to close this issue.

**Comment by JensRantil** [comment]
@kr This can be closed.

**Comment by kr** [comment]
Looks like this got taken care of.
