### ISSUE TITLE
CONTRIBUTING file

### ISSUE THREAD

**Issue by JensRantil** [kr/beanstalkd#297]
I've noticed that there occasionally are larger pull requests coming in without any issue associated with them. [Some](#296) of [them](#279) are rather large. Would it make sense to create an `CONTRIBUTING` file that asks people to changes before starting to code? Just an idea...

**Comment by kr** [comment]
Yeah a contributing file makes sense IMO. (I am not such a huge fan of the all-caps shouting style though, heh.) It's totally fine with me if people want to open a pull request without also opening an issue, as long as the change makes sense and is an improvement, etc. I used to tell people to discuss their proposals on the mailing list first, but I don't really have time to engage in design discussions there, so a github pull request is just as good in practice.

**Comment by kr** [comment]
fixed in 7628779e94f696ae9d5385c8c3bd3ac78d632dba
