### ISSUE TITLE
Proposal: Add continuous integration

### ISSUE THREAD

**Issue by JensRantil** [kr/beanstalkd#300]
Background: Out of the 35 open pull requests, almost 20 of them have no response whatsoever. This has led to some people [asking if the project is still active](#299). #297 proposes adding a `CONTRIBUTING` file to simplify contributing to this project.

Proposal: Would it make sense to run the unit tests for each pull request to easily get a glimpse of which ones are working and which ones aren't? The goal would be to make it easier to maintain this project.

**Comment by kr** [comment]
Absolutely.

**Comment by JensRantil** [comment]
Fixed in #302. Closing. Thanks!
