### ISSUE TITLE
Which protocol version is in use?

### ISSUE THREAD

**Issue by JensRantil** [kr/beanstalkd#314]
In #287, @sergeyklay asked

> Hey guys. Sorry for stupid question but I can't find protocol version. It seem to me it will be reasonable to put in a conspicuous place protocol version. What do you think about this?

Creating a separate issue (this) for his question to keep issue history clean and on topic.

**Comment by JensRantil** [comment]
In #287 @sergeyklay wrote:

> So v1.3 or v1.10 is the actual version of protocol. I'm still confused

@kr Maybe you could help clarify this?

**Comment by sergeyklay** [comment]
Oh, thanks man!

**Comment by kr** [comment]
The protocol version is inherited from the version of beanstalkd that distributes the protocol document. The version string is present in the URL of the protocol doc, if you use the release tag to link to it:

http://github.com/kr/beanstalkd/tree/v1.3/doc/protocol.txt
http://github.com/kr/beanstalkd/tree/v1.10/doc/protocol.txt
etc

(This is what we do on the [client libraries](https://github.com/kr/beanstalkd/wiki/client-libraries) page, for instance.)

**Comment by kr** [comment]
Hopefully that answered the question!
