### ISSUE TITLE
security issue / doubt

### ISSUE THREAD

**Issue by webdeveng** [kr/beanstalkd#320]
I have just started using **beanstalkd** and **pheanstalk** and I am curious whether the following situation is a security issue (and if not, why not?):

When designing a queue that will contain jobs for an eventual worker script to pick up and preform SQL database queries, I asked a friend what I could do to prevent an online user from going into port 11300 of my server, and inserting a job into the queue himself and hence causing the job to be executed with malicious code. I was told that I could include a password inside the job being sent.

Though after some time passed, I recognized that someone could preform a few simple commands on a terminal and obtain the job inside the queue, and hence find the password, and then create jobs with the password included:

    telnet thewebsitesipaddress 11300 //creating a telnet connection
    list-tubes //finding which tubes are currently being used
    use a_tube_found //using one of the tubes found
    peek-ready //see whats inside one of the jobs and find the password

What could be done to make sure this does not happen and my queue doesn't get hacked / controlled?

Thanks in advance!

**Comment by JensRantil** [comment]
@webdeveng beanstalkd is not built for being exposed to the Internet. So, don't do that! :-P If you are worried about security within your internal network (for compliance etc.) you could encrypt your payloads using a password and store the encryption key in the producer and workers (bonus points: use a public key for encryption and private key for decryption).

...and just like you said, storing a "password" within you payload seem like a really bad idea!

Feel free to close this issue if you are happy with my answer. (ping @kr)

**Comment by webdeveng** [comment]
@kr Thanks for the response JensRantil! I am assuming then that beanstalkd is meant for private networks mostly. Pheanstalk seemed perfect for my needs hahah. Would you happen to know of a common configuration / setup that could be secure but still have a producer obtaining input from online users? Either possibly blocking any IP that isn't the IP of the server to create jobs or even access the port? Or possibly to have everything in a private network but somehow have users from elsewhere activate the producer indirectly? I'm just guessing right now at what options might exist, though I have no idea if people do this in practice. Do you happen to know if any of these setups (or something similar) is common place?

**Comment by JensRantil** [comment]
> Would you happen to know of a common configuration / setup that could be secure but still have a producer obtaining input from online users?

I would say nobody exposes beanstalkd directly to the Internet ever. Best practise is to have an Internet-exposed application (such as a web application) that takes a request from your user, validates it and then puts the payload/job into beanstalkd.

**Comment by webdeveng** [comment]
Awesome, thanks for the feedback dude!
