### ISSUE TITLE
Return value of ftruncate() in filewclose() is not checked

### ISSUE THREAD

**Issue by Minnozz** [kr/beanstalkd#324]
I tried compiling beanstalkd with `-O3` (see #323), and got the following error:

```
file.c: In function ‘filewclose’:
file.c:536:9: error: ignoring return value of ‘ftruncate’, declared with attribute warn_unused_result [-Werror=unused-result]
```

The expression on that line is cast to `(void)` to suppress that warning, but according to [this discussion](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=25509) that is not actually supported.

Actually checking the return value would be preferable, although I'm not sure what should happen if the `ftruncate` fails.

My libc6 version is 2.15-0ubuntu10.15.

**Comment by kr** [comment]
We call ftruncate here to try to save a little bit of disk space, trimming off the unused part of the file at the end, when the file is almost full but can't fit any more complete records. If this operation fails, it's fine, it just means a little bit of disk space (less than 1%) might be wasted until the entire file is later deleted.

We want to ignore the return value.

If there's no way to ignore the return value, we should probably just not bother calling ftruncate at all.

**Comment by Minnozz** [comment]
I should add that only GCC (tested version 4.6.3 and 5.3.1) exhibits the behaviour described above. In clang (tested version 3.4), the `(void)` cast does successfully suppress the warning.

Since the warning (and thus error) currently only triggers when enabling compiler optimisations, I think we can safely ignore this issue for now.

Maybe it's a good idea to add `-Wno-error=unused-result` to `CFLAGS` in case a future version of GCC decides to start emitting the warning even without compiler optimisations enabled?

**Comment by kr** [comment]
> I think we can safely ignore this issue for now

Ok! Closing. We can always open a new issue if it comes up again. Thanks! 😄 

> Maybe it's a good idea to add `-Wno-error=unused-result` to `CFLAGS` 

In general, we do want that error enabled, since it can catch bugs. We never want to accidentally ignore a return value. This particular place is one of just a few (the only one?) where we deliberately ignore the return value.
