### ISSUE TITLE
socket(): Invalid argument

### ISSUE THREAD

**Issue by threesquared** [kr/beanstalkd#333]
Getting the following error on trying to start beanstalk via the service on Ubuntu 16.04. Using the `beanstalkd` package installed from apt which is version 1.10

`/usr/bin/beanstalkd: net.c:63 in make_server_socket: socket(): Invalid argument`

**Comment by threesquared** [comment]
Managed to fix this with `sudo apt-get --purge remove beanstalkd && sudo apt-get install beanstalkd`

**Comment by silviucpp** [comment]
@threesquared the version from repo it's old anyway. you might want to use the one from master.

I also created a project https://github.com/silviucpp/beanstalkd-deb where you can build your own deb and install it using `sudo apt-get -i package.deb`

Silviu
