### ISSUE TITLE
'Connection' clarification

### ISSUE THREAD

**Issue by browner12** [kr/beanstalkd#349]
Recently I've come across an issue with multiple Laravel applications on a single server. These applications happen to share the same tube names, so it is possible for one application to create a queue job, and another application to execute it.  Obviously this is not good, and results in a lot of inadvertent results.

I opened a PR for Laravel to try and correct this by automatically adding a prefix to the tube name, but this proved a little more complicated than originally thought, and was reverted for the time being.

Other queue drivers have different ways of preventing this crosstalk. For example, the database driver will be connecting specifically to your application's database.  The SQS driver has a key/secret that connects to a specific instance on your Amazon account. Redis allows you to specify a "connection".

Looking through the Beanstalkd documentation, it appears Beanstalkd also has the concept of a "connection", but I'm having trouble figuring out how to utilize it.

Was wondering if you could help shed some light on if I'm understanding Beanstalkd connections correctly, and if they would be an appropriate solution to prevent that crosstalk that I've been seeing on my server.

Thanks so much for any help you can offer.

**Comment by kr** [comment]
> Other queue drivers have different ways of preventing this crosstalk. … Redis allows you to specify a "connection".

Note that a redis connection will not help address this issue — if you have multiple applications connecting to a single redis instance, they will be able to read and write the same keys. Beanstalkd connections are like memcached or redis connections — they're just regular TCP connections. I don't think they'll help you with your issue.

Your original approach was the right thing to do: put the names used by different applications into different namespaces. This is the same technique you'd use in memcached or redis as well.

**Comment by browner12** [comment]
thanks for the response! really appreciate the help.  i'll try and address it with the prefix again
