### ISSUE TITLE
Doesn't peeking apply to subscribed tubes?

### ISSUE THREAD

**Issue by JensRantil** [kr/beanstalkd#350]
https://raw.githubusercontent.com/kr/beanstalkd/master/doc/protocol.txt states

> The peek commands let the client inspect a job in the system. There are four
variations. All but the first operate only on the currently used tube.

A client can watch multiple tubes. Shouldn't the last sentence be

> All but the first operate only on the currently used tubes.

?

**Comment by ptjm** [comment]
No, it's not currently watched tubes, but currently used tube, of which there can be only one.

**Comment by JensRantil** [comment]
I see. Thanks!
