### ISSUE TITLE
beanstalkd snap conversion 

### ISSUE THREAD

**Issue by PraveenkumarDonga** [kr/beanstalkd#352]
Hi!
I am trying to convert this beanstalkd into snap.
But I am getting this error.

![snap_error1](https://cloud.githubusercontent.com/assets/8088246/26569529/cf555f3e-4528-11e7-8708-225115929916.png)

this is my snapcraft file:

[snapcraft.txt](https://github.com/kr/beanstalkd/files/1037313/snapcraft.txt)

Could any one please help me with this.

Thanks,
Praveen

**Comment by JensRantil** [comment]
What is snap?

**Comment by PraveenkumarDonga** [comment]
it is solved :)
my snapcraft file.
[snapcraft.txt](https://github.com/kr/beanstalkd/files/1037685/snapcraft.txt)
