### ISSUE TITLE
what happen when job id reached the uint64 capacity

### ISSUE THREAD

**Issue by chrcao** [kr/beanstalkd#355]
I see beanstalkd use uint64 data type to identify a job id.
but never reset the job id. what happen when uint64 use up?

**Comment by JensRantil** [comment]
It will wrap around. That said, 2^64-1 is a _very_ large number. If you'd put 1000 jobs per second into beanstalk, it would take `(2^64-1)/1000/60/60/24/365=584942417` years before the counter wraps around. So, don't worry :)

**Comment by chrcao** [comment]
yes, it not a problem when job id use up. thanks.
hi @JensRantil 
Is this project still active current now ?

**Comment by JensRantil** [comment]
@chrcao Nice we solved that one. :smile: 

Regarding project being active, please track #299.
