### ISSUE TITLE
To get jobs size details

### ISSUE THREAD

**Issue by raju-divakaran** [kr/beanstalkd#358]
Hello,

I don't know if this is the right place to post this! 

I am maintaining beanstalk service ( version used is 1.9 ), where there are more than 2000 tubes and millions of messages been handled. Recently I started noticing that jobs are not getting retried or removed as it used to happen. As a result the mount for storing bin logs are consuming more space. Then I've to kick jobs from delayed tubes. 

Can someone tell me, how I can understand 

- Which delayed tube is slackened 
- Which tube is having jobs of bigger size
- How to get job id

Thanks

**Comment by JensRantil** [comment]
Hi @raju-divakaran, I am not the maintainer of this project, but I can tell you that you are posting your question in the right place. You might also want to try reaching out to the beanstalkd user mailing list.

**Comment by raju-divakaran** [comment]
Thanks for the suggestion guys!
