### ISSUE TITLE
touch($id) method

### ISSUE THREAD

**Issue by andygithubchen** [kr/beanstalkd#365]
"touch($id)" method how to use? Can you give an example? thank you all

**Comment by JensRantil** [comment]
Have you checked out https://github.com/kr/beanstalkd/blob/master/doc/protocol.txt#L316?

**Comment by andygithubchen** [comment]
@JensRantil  thank you ！

**Comment by JensRantil** [comment]
@andygithubchen No worries. Feel free to close this issue.
