### ISSUE TITLE
Overflow in read_delay

### ISSUE THREAD

**Issue by Erikvv** [kr/beanstalkd#368]
in prot.c:
```
static int
read_delay(int64 *delay, const char *buf, char **end)
{
    int r;
    uint delay_sec;

    r = read_pri(&delay_sec, buf, end);
    if (r) return r;
    *delay = ((int64) delay_sec) * 1000000000;
    return 0;
}
```
The multiplication by 1 billion can overflow.

Also later a deadline unix timestamp in nanoseconds is calculated, this will overflow when the number of seconds delay is bigger than `int64_max / 1.000.000.000 - time(NULL)` = 7710979059 seconds = ~244 years

So in the year 2261 the delay feature won't work at all any more but I guess thats a known thing.

**Comment by kr** [comment]
Thanks for reporting this.

The intention was for `delay_sec` to be a 32-bit value, and although `uint` is 32 bits on many systems in practice, that's not guaranteed. It should be declared as `uint32` and the conversion in `read_pri` should check the range explicitly.

**Comment by Erikvv** [comment]
What I'm seeing is negative job delays. I think the problem may be in the cast from unsigned to signed. Though I didn't dig that deep and I don't do much C programming.

**Comment by kr** [comment]
Are you providing large delays? If your delay is less than 9,223,372,036,854 seconds (that is over 290 thousand years), then you should not be experiencing overflow here.

**Comment by Erikvv** [comment]
Yes the delays are large due to a botched binary backoff implementation in the PHP client. 

But they are not that thousands of years. It seems to me anything over pow(2, 31) can produce a negative delay: http://codepad.org/6aLoSNAv

Should be easy to reproduce but I don't have a machine at this very moment.

**Comment by kr** [comment]
Note that the code in http://codepad.org/6aLoSNAv is doing arithmetic on the uint value; the beanstalkd code you quoted above isn't. So this is not an apples-to-apples comparison.

**Comment by Erikvv** [comment]
I was not able to reproduce it.

In our product we have fixed both the binary back-off and the issue that caused the jobs to be delayed in the first place. So it is no longer taking place. 

And now I have just way too many variables to rule out.

I also suspect PHP code may have been the culprit:

```
php > $var = 92233720368547758070;
php > echo $var;
9.2233720368548E+19
php > echo sprintf("delay by %u", $var);
delay by 0
```
