### ISSUE TITLE
Multiple listen adresses

### ISSUE THREAD

**Issue by nicolas-t** [kr/beanstalkd#372]
Hello

currently my `/etc/default/beanstalkd` contains this : 
```
BEANSTALKD_LISTEN_ADDR=127.0.0.1
```

But i'd like a second server to be able to perform jobs.
Can I do something like this? : 

```
BEANSTALKD_LISTEN_ADDR=[127.0.0.1, remote_worker_ip]
```

Or do I have to open it like this : 
```
BEANSTALKD_LISTEN_ADDR=0.0.0.0
```
And then whitelist `remote_worker_ip` with iptables ? What are the good practices ?

Thanks

**Comment by JensRantil** [comment]
First off, `/etc/default/beanstalkd` is not maintained by the Github repository. If you have specific questions about it, please contact the Linux distribution package maintainer for the beanstalkd package.

Above said, `beanstalkd` only supports a single listen adress (`-l` flag, execute `beanstalkd -help` for a full list of flags). So, you will need to go with the

    BEANSTALKD_LISTEN_ADDR=0.0.0.0

approach if you need to listen on multiple IP addresses, and then do white och blacklisting in your favourite firewall.

Feel free to close this issue if you believe I answered your question.

**Comment by nicolas-t** [comment]
Thanks :)

**Comment by Bilge** [comment]
Just because the OP did not understand that `/etc/default/beanstalkd` is not part of beanstalkd does not obviate the need to support multiple addresses.
