### ISSUE TITLE
Replacing current beanstalkd-cli tool on wiki page

### ISSUE THREAD

**Issue by EdwinHoksberg** [kr/beanstalkd#373]
Hi, currently the link on the wiki page for a cli tool is directing to this repo: https://github.com/schickling/beanstalkd-cli/
However, that program hasn't been updated for a long time(3 years, the latest patch 6 months ago was by me and was a grammar fix), and the build is also failing. So I would like to change it to a program I wrote a few days ago(and plan on maintaining, we use it in prod); https://github.com/EdwinHoksberg/beanstalkd-cli

I could just modify the wiki page by myself but because I would remove a link and replace it with mine I just wanted to let you know and make sure you agree.
Thanks!

**Comment by kr** [comment]
Fine by me. :)
