### ISSUE TITLE
Priorities for workers

### ISSUE THREAD

**Issue by john-dev** [kr/beanstalkd#374]
Hey there,

is it possible to add priorities for workers aswell?
Maybe by using a kind of reserve-delays for for each worker?

We use faster and slower hardware and want to process as much as possible on the fast hardware.

Thanks

**Comment by JensRantil** [comment]
@john-dev How about your slow workers periodically reserve a job and check when it was added. If more than a few seconds, the worker processes otherwise, it quickly puts it back on queue for a fast processor to process it?

**Comment by john-dev** [comment]
Hey Jens,

that's a nice workaround for sure.. good idea :-)
Even tho i don't like to implement a worker-based solution into the software itself (since it is not always possible and "strange" to configure different priorities), it will work yes

**Comment by mlbarrow** [comment]
I argue that it would be strange to have to encode this logic into the
queue server. In theory, if those workers are slow, they will naturally not
get a lot of the jobs because the faster workers will chew through the work
and be done first. Has that not been your experience?

*michael at barrow dot me*
+1.541.600.2027

"Do not anticipate trouble, or
worry about what may never happen.
Keep in the sunlight." -- B. Franklin

**Comment by john-dev** [comment]
No, not at all to be honest..
We render proxy files of videos for events on demand (watchfolder).. The bandwith of all machines is the same, but the graphic card is not (we use 1060, 1070 and 1080)..

I don't think it's a bad idea to implement something like job.reserve(timeout = 5, delay = 5) to simulate priorities to be honest..

**Comment by john-dev** [comment]
Ah sorry, i missread your answer..
Sure, this is true, but still, since we have times in which we have like 5 videos a days (all are time ciritical), they all should be handled by the fastest server..

**Comment by JensRantil** [comment]
> job.reserve(timeout = 5, delay = 5)

@john-dev It feels unintuitive to _add_ a delay for something that is latency critical,  no? Sure, you might wait 5 seconds to find the fastest encoder and it processes the video for 5 min or whatever, but then what is the probability of multiple processors being ready within those five seconds?

Also, isn't video encoded in same-size chunks anyway? If so, it's a highly parallelizable problem anyway and your latency is basically a function of the slowest processor?

**Comment by john-dev** [comment]
I don't think that this is so unintuitive to be honest, but i might be wrong.
It's not just about video encoding, this was just an example which you can apply on a lot of tasks - for example machines doing up & downloads with different bandwith etc.

This delay change would add support for asymmetric load instead of round robin if you use beanstalkd as loadbalancer, something, beanstalkd has been designed for..

Anyway, i implent you first approach into my workers, but in general, i still see this as a nice feature.
Thanks!
