### ISSUE TITLE
How can I connect to beanstalk and get deail job info

### ISSUE THREAD

**Issue by pain400** [kr/beanstalkd#375]
There are some failed jobs in queue, and I want to check the detail job info. There are some commands provided to list job detail info?

**Comment by JensRantil** [comment]
Have a look at https://github.com/kr/beanstalkd/blob/master/doc/protocol.txt. Specifically, you likely want to look at `stats-job`. You can't look at the job payload. I suggest you bury the failed jobs so you can use `peek-buried` to look at the buried jobs.

**Comment by kr** [comment]
You can also use `peek 123` to get the job payload (where '123' is the job id).

**Comment by pain400** [comment]
@JensRantil Thanks, the doc is very detailed. I run the command `stats-tube default` and output somethings as following:

`OK 267
---
name: default
current-jobs-urgent: 0
current-jobs-ready: 0
current-jobs-reserved: 0
current-jobs-delayed: 0
current-jobs-buried: 0
total-jobs: 69
current-using: 5
current-watching: 5
current-waiting: 0
cmd-delete: 69
cmd-pause-tube: 0
pause: 0
pause-time-left: 0
`

I seems like there are no jobs in the queue, but I run the command `php artisan queue:failed` to list failed jobs and output something as following:

+----+------------+---------+---------------------------------------+---------------------+
| ID | Connection | Queue   | Class                                 | Failed At           |
+----+------------+---------+---------------------------------------+---------------------+
| 3  | beanstalkd | default | App\Jobs\Request\CreateNotifyManager  | 2018-03-09 18:45:16 |
| 2  | beanstalkd | default | App\Jobs\Request\CreateNotifyManager  | 2018-03-08 17:44:11 |
| 1  | beanstalkd | default | App\Jobs\Request\CreateNotifyManager  | 2017-08-31 17:16:20 |
+----+------------+---------+---------------------------------------+---------------------+

Why I can not get these failed jobs by connect beanstalkd

**Comment by JensRantil** [comment]
@pain400 `current-watching: 5` and `current-using: 5` hints that you have other tubes than the default. Have you listed the tubes and also run `stats-tube` on those tubes?

**Comment by pain400** [comment]
@JensRantil How can I list all tubes, I get only the default tube by running `list-tubes`, the output as following:

OK 14

- default

Isn't the failed jobs stored in the queue?

**Comment by JensRantil** [comment]
> Isn't the failed jobs stored in the queue or there are other command to list all tubes?

It might. Or it's buried depending on your beanstalkd client logic.

**Comment by pain400** [comment]
Ok, thanks!
